version: '3.9'
services:
  db-mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=azota
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - mysql_azota_data:/var/lib/mysql
volumes:
  mysql_azota_data:
    external: true